use_frameworks!

target 'MSWatchSession_Example' do
  use_frameworks!
  platform :ios, '13.0'

  pod 'MSWatchSession', :path => '../'

end

target 'MSWatchSessionWatchApp_Example Watch App' do
  use_frameworks!
  platform :watchos, '10.0'

  pod 'MSWatchSession', :path => '../'

end

